error: Use JSProtoKey to get Error constructor
Instead of looking up the Error prototype by name on the global object
when we want to throw an error, use JS_GetClassObject and JSProtoKey to
avoid the conversion of string to ID and the property lookup.