testCommandLine.sh: Skip a Gio.Subprocess test when inside of a circleci environment.
It fails with:
GLib.SpawnError: Failed to close file descriptor for child process
(Operation not permitted)

It passes in a local circleci build so it seems related to the
hosted service.