gerror: Define toString() for boxed GErrors
If you create a GError with the default GLib.Error constructor (which
translates to g_error_new_literal() in C) you end up with a slightly
strange error object, with a Boxed* private pointer instead of an Error*
private pointer. This error object doesn't have the usual properties that
are expected on a JS exception (such as 'stack', etc.) and doesn't have a
nice toString() function.

Previously there was a special case in gjs_log_exception() for printing
these objects. We move this special case to the GError toString()
function, so that the correct behaviour is available whenever you print
the object, not just in gjs_log_exception().

In order to catch this case, we have to special case G_TYPE_ERROR in the
boxed_new() function.

https://github.com/GNOME/gjs/commit/8da83b72b1444ab7b574d39452151b07a37431a5