gerror: Split gjs_throw_g_error()
This moves gjs_throw_g_error() to gi/gerror.cpp (and renames it
gjs_throw_gerror() for consistency with the other functions in that
file.)

We also create gjs_throw_gerror_message() which we use in a situation
where we don't have to marshal the GError into JavaScript. It simply
copies the GError message into a regular JavaScript Exception object.
This should be used inside internal functions, for example while
converting strings to bytes, where the caller wouldn't necessarily expect
to receive a GError.

This allows more decoupling of the jsapi-util-* files from the
gobject-introspection stuff.